### ISSUE TITLE
memory/file option callbacks should be optional

### ISSUE THREAD

**Issue by AODQ** [maxxnino/cgltf-zig#2]
Commit fe64fc0677fdabba124cbc5af319a366e27e7f3f  changed
```
    alloc: ?fn (?*anyopaque, usize) callconv(.C) ?*anyopaque,
    free: ?fn (?*anyopaque, ?*anyopaque) callconv(.C) void,
    read: ?fn ([*c]const MemoryOption, [*c]const FileOption, [*c]const u8, [*c]usize, [*c]?*anyopaque) callconv(.C) Result,
    release: ?fn ([*c]const MemoryOption, [*c]const FileOption, ?*anyopaque) callconv(.C) void,
```
to
```
    alloc: fn (*anyopaque, usize) callconv(.C) ?*anyopaque,
    free: fn (*anyopaque, *anyopaque) callconv(.C) void,
    read: fn (*const MemoryOption, *const FileOption, [*:0]const u8, [*c]usize, [*c]?*anyopaque) callconv(.C) Result,
    release: fn (*const MemoryOption, *const FileOption, ?*anyopaque) callconv(.C) void,
```

However, I think these should remain optional. It is valid to pass null into these fields (and is done in the example of cgltf's readme), otherwise there is no option to use cgltf's default behavior. I don't see why this option should be removed, unless there  are `makeDefaultMemoryOption(alloc : std.mem.Allocator)` and `makeDefaultFileOption()` that the bindings can provide.

**Comment by maxxnino** [comment]
Hi, thank for the suggestion. It just a results from 30 min of works. So it's may only correct on some of the function i use. The rest is base on feeling. A pr would be welcome

**Comment by AODQ** [comment]
There are some other missing optionals like
```
    skin: ?*Skin,
    mesh: ?*Mesh,
    camera: ?*Camera,
    light: ?*Light,
```
in `Node` (a node doesn't need to have any of these properties), i'll look for other missing optionals & see if I can do a PR

**Comment by maxxnino** [comment]
Thank you, really appreciated. You seem have more knowledge than me when coming to cgltf. I can give you write access to this repo. And we can maintain the repo together.

**Comment by maxxnino** [comment]
@AODQ  Hi I just updated the repo https://github.com/maxxnino/cgltf-zig/commit/652a23708811b0e501db5ec51cdabcb4a14d6c4a. I'm using gltf 2.0 spec as reference. But there are some items cgltf have but gltf 2.0 spec is missing

**Comment by AODQ** [comment]
Nice, this looks good. Yes some stuff like `Light`, some materials, draco compression, etc won't be available on the glTF spec because they are extensions https://github.com/KhronosGroup/glTF/tree/main/extensions

**Comment by maxxnino** [comment]
Thank you, will take a look when I need it
